name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '11.12.x'
    - name: yarn install
      run: yarn install
    - name: run lint
      run: yarn run lint
